### ISSUE TITLE
413 Entity too large

### ISSUE THREAD

**Issue by danlindow** [santthosh/aws-es-kibana#18]
I am leveraging a proxy solution upstream of this service. Unfortunately my proxy inserts some rather large cookies and headers.  I believe express is not happy about the size of the request header and is returning a 413 entity too large.  Is there any option we can use to tune the request body or headers maximum size?  Sorry if this has been asked already, I am not too familiar with NodeJS.

**Comment by danlindow** [comment]
So after much further testing I discovered that this appears to be an AWS ES issue.  The cookie header was too large that AWS ES returns a 413 back to the user. This is not related to this proxy.

**Comment by dewdo** [comment]
I am currently experiencing the same issue. How do you solve that if it's on AWS side ?

**Comment by danlindow** [comment]
Since kibaba does not rely on cookies you can strip the entire cookie
header as it is sent to AWS ES. I am using Nginx to do the manipulation.
