### ISSUE TITLE
Security Key Invalid Error

### ISSUE THREAD

**Issue by iammohan83** [santthosh/aws-es-kibana#19]
Hi ,

i am getting error as security key invalid when we try to access using AWS STS credentials. But using that profile credentials i am able to access all aws services. I am using that same role in other programs for signing it works fine. When i try to use the same credentials in aws-es-kibana  getting security key invalid error. Kindly some one help me to solve this issue.

Mohan

**Comment by abigpotostew** [comment]
Same problem. This was working, but now amazon rejects it with message "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method."

**Comment by shanloid** [comment]
Seeing the same problem. This was working until very recently. We migrated to [an alternative proxy](https://github.com/abutaha/aws-es-proxy), which doesn't seem to suffer from this issue.

**Comment by nlv09165** [comment]
Had the same problem, but the cause was the wrong use of the proxy.
The endpoint argument should be the hostname part of the URL!
This fixed the issue for me.
so instead of:
```
aws-es-kibana https://search-xxxxxxxxxxxxxxxxxxxxx.eu-west-1.es.amazonaws.com
```
you should do:
```
aws-es-kibana search-xxxxxxxxxxxxxxxxxxxxx.eu-west-1.es.amazonaws.com
```

**Comment by santthosh** [comment]
Resolved, Please drop protocol Thanks @nlv09165
