### ISSUE TITLE
sigv4 host causing failure in aws

### ISSUE THREAD

**Issue by cgballance** [santthosh/aws-es-kibana#27]
looks like the Host var that you put the ENDPOINT in is now being parsed in ES.(on host it is https).
i fixed by:
npm install url -save
require('url') in index.js
add line to index.js
var TARGETHOST = url.parse(TARGET).hostname;
Use that for populating Host header.

**Comment by inno-ron** [comment]
Ran into this as well, you can just change it to:
request.headers['Host'] = ENDPOINT.split("://")[0];

**Comment by santthosh** [comment]
This has been fixed with #23
