### ISSUE TITLE
Not Working with AWS IAM Roles

### ISSUE THREAD

**Issue by markusbecker** [santthosh/aws-es-kibana#29]
Hey guys,

im not really sure if this is intended or not but aws-es-kibana doesnt seem to work with CLI profiles which includes roles like the following construct.

```
[xxx-logon]
aws_access_key_id = xxx
aws_secret_access_key = xxx

[es-test]
role_arn = arn:aws:iam::xxxxx:role/es_test
source_profile = xxx-logon
```

When i use AWS_PROFILE=es-test the webserver is giving me the following return:

> {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'GET\n/\n\nhost:https\nx-amz-date:20170725T142058Z\nx-amz-security-................

Is anyone one of you working with roles instead of local users?

Best regards,
Markus

**Comment by markusbecker** [comment]
For further notice: Doing the assume role on my own and storing the following variables in env does work:

$env:AWS_ACCESS_KEY_ID=$tempcred.Credentials.AccessKeyId
$env:AWS_SECRET_ACCESS_KEY=$tempcred.Credentials.SecretAccessKey
$env:AWS_SESSION_TOKEN=$tempcred.Credentials.SessionToken

**Comment by drrzmr** [comment]
same problem here :(

**Comment by taxpon** [comment]
Same problemz..

**Comment by drrzmr** [comment]
this works fine here: https://github.com/abutaha/aws-es-proxy

**Comment by Amit-A** [comment]
Same problem here

**Comment by cortopy** [comment]
I've spent some "good" few hours on this. It appears this package has not been updated for a long while and there not one, not two, but three awaiting pull requests that would solve the issue!!!

In my case my error was writing the endpoint with https://. Either apply https://github.com/santthosh/aws-es-kibana/pull/23 or just remove it. Other pull requests do different things
