### ISSUE TITLE
Does not bind to correct IP on Heroku

### ISSUE THREAD

**Issue by kurisu** [santthosh/aws-es-kibana#30]
When starting this up on heroku, aws-es-kibana binds to 127.0.0.1 (local loopback), which heroku obviously isn't looking at, so 60 seconds later, we get this:

`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`

Workaround: set the BIND_ADDRESS config (env) to 0.0.0.0, which for sure will bind to the address heroku can see.  Confirmed this fixed the issue for us.

Suggestion: Bind to 0.0.0.0 by default (less secure in general, but fixes the problem on heroku)

**Comment by santthosh** [comment]
This has been fixed with #38
