### ISSUE TITLE
Question: Could your provide example of setting AWS_PROFILE?

### ISSUE THREAD

**Issue by yeryomenkom** [santthosh/aws-es-kibana#33]
Could your provide example of AWS_PROFILE setting? I mean the full string.
I use docker compose on my AWS instance and aws-es-kibana docker image.
Always get: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method."

**Comment by Johnius** [comment]
Same!

**Comment by momota10** [comment]
Same!

**Comment by hassankhan** [comment]
Usually its just something like:

```bash
export AWS_PROFILE=MyWorkProfile
```

where `MyWorkProfile` is an AWS profile under `~/.aws/credentials` on your machine.

**Comment by cortopy** [comment]
I've spent some "good" few hours on this. It appears this package has not been updated for a long while and there not one, not two, but three awaiting pull requests that would solve the issue!!!

In my case my error was writing the endpoint with https://. Either apply https://github.com/santthosh/aws-es-kibana/pull/23 or just remove it

**Comment by santthosh** [comment]
#23  has been applied, Thanks
