### ISSUE TITLE
aws-es-kibana on Docker hub

### ISSUE THREAD

**Issue by nicodeur** [santthosh/aws-es-kibana#41]
Hi,

It would be usefull to push regulary aws-es-kibana on your own Docker hub.

Indeed, I use `aws-es-kibana` with Jenkins. I would like to have automaticaly fresh `aws-es-kibana` without manual action.

To day, I build docker `aws-es-kibana` on my computer and push it on my own docker hub. Jenkins use this image to push on kibana. It's not very clean.

Thanks for advance

**Comment by santthosh** [comment]
Thanks @nicodeur, have done that. aws-es-kibana is now available from [Dockerhub](https://hub.docker.com/r/santthosh/aws-es-kibana/). Added to documentation in README.md as well
