### ISSUE TITLE
basic http authentication disabled

### ISSUE THREAD

**Issue by amircodota** [santthosh/aws-es-kibana#43]
I think [this](https://github.com/santthosh/aws-es-kibana/commit/4861bfa19cb86c677f4c1a88118554eae8afeb62) commit completely disabled http authantication.

This leaves ES completely open to the public, even when deployed on heroku.

Am I missing something?

Amir

**Comment by amenadiel** [comment]
I noticed the same. Left a PR #44

**Comment by santthosh** [comment]
@amenadiel Please verify and let me know if this works now with the latest (1.0.7) - Thanks
